package com.springboot.isotool.util;

public class ISOConstants {
	
	public static final String RECORD_NOT_FOUND = "Record Not Found";
	public static final String DATA_NOT_FOUND = "Data Element not Found";
	public static final String ERROR ="Error Occurred";
	public static final String element38 = "A unique code assigned by the issuer/NPCI for a successful transaction. This is a 6 character authorization code generated by the issuer / NPCI and should not be filled by the acquirer For domestic transactions, this field should not contain all zeroes or all blank spaces or special character in response.";

}
